// Team Performance Dashboard Data
// Realistic dummy data for 8 sales representatives

export interface SalesRep {
  id: string;
  name: string;
  initials: string;
}

export interface ResultsPipelineData {
  repName: string;
  pipelineGenerated: number;
  quotaAttainment: number;
}

export interface MRRResultsData {
  repName: string;
  week1: number;
  week2: number;
  week3: number;
  week4: number;
}

export interface PipelineWeeklyData {
  repName: string;
  week1: number;
  week2: number;
  week3: number;
  week4: number;
}

export interface ActivityWeeklyData {
  repName: string;
  calls: { week1: number; week2: number; week3: number; week4: number };
  p2sTouched: { week1: number; week2: number; week3: number; week4: number };
  igaMeetings: { week1: number; week2: number; week3: number; week4: number };
}

export interface ContactsEngagedData {
  repName: string;
  average: number;
}

export interface OutreachByPersonaData {
  repName: string;
  decisionMaker: number;
  influencer: number;
  other: number;
}

export interface P1StatusData {
  repName: string;
  overSLA: number;
  unworked: number;
  inProgress: number;
}

export interface SpeedDepthData {
  repName: string;
  speed: number; // % contacted < 24hrs
  depth: number; // % receiving 5 touches in 14 days
}

export interface P2DepthData {
  repName: string;
  depthPercent: number;
}

export interface P3ChannelMixData {
  repName: string;
  channelCompliance: number; // % with call + email
  volumeCompliance: number; // % with 4 touches / 14 days
}

export const salesReps: SalesRep[] = [
  { id: "rep-1", name: "Sarah Chen", initials: "SC" },
  { id: "rep-2", name: "Marcus Johnson", initials: "MJ" },
  { id: "rep-3", name: "Emily Rodriguez", initials: "ER" },
  { id: "rep-4", name: "David Kim", initials: "DK" },
  { id: "rep-5", name: "Jessica Williams", initials: "JW" },
  { id: "rep-6", name: "Michael Brown", initials: "MB" },
  { id: "rep-7", name: "Amanda Taylor", initials: "AT" },
  { id: "rep-8", name: "Chris Martinez", initials: "CM" },
];

export const resultsPipelineData: ResultsPipelineData[] = [
  { repName: "Sarah Chen", pipelineGenerated: 285000, quotaAttainment: 112 },
  { repName: "Marcus Johnson", pipelineGenerated: 195000, quotaAttainment: 78 },
  { repName: "Emily Rodriguez", pipelineGenerated: 320000, quotaAttainment: 128 },
  { repName: "David Kim", pipelineGenerated: 156000, quotaAttainment: 62 },
  { repName: "Jessica Williams", pipelineGenerated: 248000, quotaAttainment: 99 },
  { repName: "Michael Brown", pipelineGenerated: 178000, quotaAttainment: 71 },
  { repName: "Amanda Taylor", pipelineGenerated: 290000, quotaAttainment: 116 },
  { repName: "Chris Martinez", pipelineGenerated: 210000, quotaAttainment: 84 },
];

// MRR closed by week of month (in dollars)
export const mrrResultsData: MRRResultsData[] = [
  { repName: "Sarah Chen", week1: 12500, week2: 18200, week3: 15800, week4: 22500 },
  { repName: "Marcus Johnson", week1: 8200, week2: 11500, week3: 9800, week4: 14200 },
  { repName: "Emily Rodriguez", week1: 15800, week2: 21000, week3: 18500, week4: 25800 },
  { repName: "David Kim", week1: 5200, week2: 7800, week3: 6500, week4: 9200 },
  { repName: "Jessica Williams", week1: 11200, week2: 14800, week3: 13200, week4: 18500 },
  { repName: "Michael Brown", week1: 7500, week2: 10200, week3: 8800, week4: 12500 },
  { repName: "Amanda Taylor", week1: 14200, week2: 19500, week3: 16800, week4: 23200 },
  { repName: "Chris Martinez", week1: 9500, week2: 12800, week3: 11200, week4: 15800 },
];

// Monthly MRR target per rep
export const mrrTarget = 55000;

// Pipeline generated by week of month (in dollars)
export const pipelineWeeklyData: PipelineWeeklyData[] = [
  { repName: "Sarah Chen", week1: 65000, week2: 78000, week3: 72000, week4: 70000 },
  { repName: "Marcus Johnson", week1: 42000, week2: 55000, week3: 48000, week4: 50000 },
  { repName: "Emily Rodriguez", week1: 75000, week2: 88000, week3: 82000, week4: 75000 },
  { repName: "David Kim", week1: 35000, week2: 42000, week3: 38000, week4: 41000 },
  { repName: "Jessica Williams", week1: 58000, week2: 68000, week3: 62000, week4: 60000 },
  { repName: "Michael Brown", week1: 40000, week2: 48000, week3: 45000, week4: 45000 },
  { repName: "Amanda Taylor", week1: 68000, week2: 78000, week3: 72000, week4: 72000 },
  { repName: "Chris Martinez", week1: 48000, week2: 58000, week3: 52000, week4: 52000 },
];

// Monthly pipeline target per rep
export const pipelineTarget = 250000;

export const activityWeeklyData: ActivityWeeklyData[] = [
  { repName: "Sarah Chen", calls: { week1: 42, week2: 38, week3: 45, week4: 41 }, p2sTouched: { week1: 18, week2: 21, week3: 15, week4: 22 }, igaMeetings: { week1: 4, week2: 5, week3: 3, week4: 6 } },
  { repName: "Marcus Johnson", calls: { week1: 28, week2: 32, week3: 25, week4: 30 }, p2sTouched: { week1: 10, week2: 12, week3: 8, week4: 14 }, igaMeetings: { week1: 2, week2: 3, week3: 2, week4: 3 } },
  { repName: "Emily Rodriguez", calls: { week1: 48, week2: 52, week3: 50, week4: 55 }, p2sTouched: { week1: 22, week2: 25, week3: 20, week4: 24 }, igaMeetings: { week1: 5, week2: 6, week3: 5, week4: 7 } },
  { repName: "David Kim", calls: { week1: 18, week2: 22, week3: 15, week4: 20 }, p2sTouched: { week1: 6, week2: 8, week3: 5, week4: 9 }, igaMeetings: { week1: 1, week2: 2, week3: 1, week4: 2 } },
  { repName: "Jessica Williams", calls: { week1: 35, week2: 40, week3: 38, week4: 42 }, p2sTouched: { week1: 14, week2: 17, week3: 13, week4: 18 }, igaMeetings: { week1: 3, week2: 4, week3: 3, week4: 4 } },
  { repName: "Michael Brown", calls: { week1: 25, week2: 28, week3: 22, week4: 30 }, p2sTouched: { week1: 9, week2: 11, week3: 7, week4: 13 }, igaMeetings: { week1: 2, week2: 2, week3: 2, week4: 3 } },
  { repName: "Amanda Taylor", calls: { week1: 45, week2: 48, week3: 42, week4: 50 }, p2sTouched: { week1: 19, week2: 23, week3: 17, week4: 21 }, igaMeetings: { week1: 4, week2: 5, week3: 4, week4: 5 } },
  { repName: "Chris Martinez", calls: { week1: 32, week2: 35, week3: 30, week4: 38 }, p2sTouched: { week1: 12, week2: 15, week3: 10, week4: 16 }, igaMeetings: { week1: 3, week2: 3, week3: 2, week4: 4 } },
];

export const contactsEngagedData: ContactsEngagedData[] = [
  { repName: "Sarah Chen", average: 5.2 },
  { repName: "Marcus Johnson", average: 3.1 },
  { repName: "Emily Rodriguez", average: 6.4 },
  { repName: "David Kim", average: 2.3 },
  { repName: "Jessica Williams", average: 4.5 },
  { repName: "Michael Brown", average: 3.4 },
  { repName: "Amanda Taylor", average: 5.1 },
  { repName: "Chris Martinez", average: 4.0 },
];

export const outreachByPersonaData: OutreachByPersonaData[] = [
  { repName: "Sarah Chen", decisionMaker: 45, influencer: 35, other: 20 },
  { repName: "Marcus Johnson", decisionMaker: 30, influencer: 40, other: 30 },
  { repName: "Emily Rodriguez", decisionMaker: 55, influencer: 30, other: 15 },
  { repName: "David Kim", decisionMaker: 25, influencer: 35, other: 40 },
  { repName: "Jessica Williams", decisionMaker: 40, influencer: 38, other: 22 },
  { repName: "Michael Brown", decisionMaker: 35, influencer: 40, other: 25 },
  { repName: "Amanda Taylor", decisionMaker: 50, influencer: 32, other: 18 },
  { repName: "Chris Martinez", decisionMaker: 38, influencer: 37, other: 25 },
];

export const p1StatusData: P1StatusData[] = [
  { repName: "Sarah Chen", overSLA: 2, unworked: 3, inProgress: 15 },
  { repName: "Marcus Johnson", overSLA: 5, unworked: 7, inProgress: 8 },
  { repName: "Emily Rodriguez", overSLA: 1, unworked: 2, inProgress: 17 },
  { repName: "David Kim", overSLA: 8, unworked: 10, inProgress: 2 },
  { repName: "Jessica Williams", overSLA: 3, unworked: 4, inProgress: 13 },
  { repName: "Michael Brown", overSLA: 6, unworked: 5, inProgress: 9 },
  { repName: "Amanda Taylor", overSLA: 2, unworked: 3, inProgress: 15 },
  { repName: "Chris Martinez", overSLA: 4, unworked: 6, inProgress: 10 },
];

export const speedDepthData: SpeedDepthData[] = [
  { repName: "Sarah Chen", speed: 72, depth: 68 },
  { repName: "Marcus Johnson", speed: 45, depth: 38 },
  { repName: "Emily Rodriguez", speed: 85, depth: 78 },
  { repName: "David Kim", speed: 28, depth: 22 },
  { repName: "Jessica Williams", speed: 62, depth: 58 },
  { repName: "Michael Brown", speed: 48, depth: 42 },
  { repName: "Amanda Taylor", speed: 75, depth: 72 },
  { repName: "Chris Martinez", speed: 55, depth: 48 },
];

export const p2DepthData: P2DepthData[] = [
  { repName: "Sarah Chen", depthPercent: 88 },
  { repName: "Marcus Johnson", depthPercent: 52 },
  { repName: "Emily Rodriguez", depthPercent: 95 },
  { repName: "David Kim", depthPercent: 35 },
  { repName: "Jessica Williams", depthPercent: 72 },
  { repName: "Michael Brown", depthPercent: 58 },
  { repName: "Amanda Taylor", depthPercent: 85 },
  { repName: "Chris Martinez", depthPercent: 65 },
];

export const p3ChannelMixData: P3ChannelMixData[] = [
  { repName: "Sarah Chen", channelCompliance: 82, volumeCompliance: 75 },
  { repName: "Marcus Johnson", channelCompliance: 55, volumeCompliance: 48 },
  { repName: "Emily Rodriguez", channelCompliance: 90, volumeCompliance: 85 },
  { repName: "David Kim", channelCompliance: 38, volumeCompliance: 32 },
  { repName: "Jessica Williams", channelCompliance: 70, volumeCompliance: 65 },
  { repName: "Michael Brown", channelCompliance: 58, volumeCompliance: 52 },
  { repName: "Amanda Taylor", channelCompliance: 85, volumeCompliance: 78 },
  { repName: "Chris Martinez", channelCompliance: 62, volumeCompliance: 58 },
];
